### ISSUE TITLE
Duplicate value

### ISSUE THREAD

**Issue by laruche** [AkashBabu/redis-json#22]
Hi team 

My bug is really strange :) 

I use Redis-json to store large dataset (api cache) for my ecommerce middle office
I call api wich return array of data, and i store it on redis after conversion in object 
with this function

`
obj = obj.reduce((r, o) => ((r[o.id] = o), r), []);
obj = Object.assign({}, obj);
await jsonCache.set(keyCache, obj);
`

I use a conversion before insertion in order to edit specific data with there ID
I this case I use : 

`
var object = {};
object[key] = obj;
await jsonCache.set(keyCache, object)
`

In my test, with few data it's work !
but, ... with production (8MO json)
there is a duplicate when I retrieve all data !
But if I use 

`var text = await jsonCache.get(keyCache, key);;`

edited value is well in place 

4 hours of research... need your help !

**Comment by AkashBabu** [comment]
Hi @laruche , firstly I'm really sorry that I replying too late.

If my understanding is right, then you are doing the following:
```JS
const apiResponse = [{id: 1, data: any}, {id: 2, data: any}, {id: 3, data: any}]
const output = apiResponse.reduce((result, item) => result[item.id] = item, {})
// output -> {1: {id: 1, data: any}, 2: {id: 2, data: any}, 3: {id: 3, data: any}}

// Now you modify some data before insertion
output[1].data = someotherData;

// Save the data
await jsonCache.set(keyCache, output);
```
Now I would like to understand where exactly are you facing duplicate data issue ?
Also please specify the path like: read cache -> modify data -> update cache ?
Please answer the above questions, so that I will be able to help with your issue.

**Comment by AkashBabu** [comment]
Closing this issue as no response has been received since a month
