### ISSUE TITLE
TypeError: redis_json_1.default is not a constructor

### ISSUE THREAD

**Issue by rouzbehsbz** [AkashBabu/redis-json#26]
Hi, recently I installed `redis-json` package but when I try to run my code that compiled with typescript it throws following error:
```
const redisJson = new redis_json_1.default(redis);
                  ^

TypeError: redis_json_1.default is not a constructor
```

Here's my code, all I done is just installing `redis` and `redis-json`:
```
import {createClient} from 'redis';
import JSONCache from 'redis-json';

const redis = createClient();
const redisJson = new JSONCache(redis);
```

also this is my `tsconfig.json` as well:
```
{
  "compilerOptions": {
      "module": "commonjs",
      "resolveJsonModule": true,
      "target": "es6",
      "outDir": "dist"
  },
  "include": [
      "./src/**/*"
  ],
  "exclude": [
      "node_modules"
  ]
}
```

I try to enable `esModuleInterop` but other packages get error.
I'm not sure is this an issue with `redis-json` package or typescript, but I hope I can get some help here. thank you.
also my Node.js version is `14.17.3`. and I'm using Typescript version `4.3.5`

**Comment by AkashBabu** [comment]
Hi @rouzbehsbz , this isn't an issue with `redis-json` library as such, I tried your config and was able to reproduce the same issue, but the issue was fixed when `esModuleInterop` was enabled. Not sure why other packages are throwing errors.
For quicker resolution on Typescript issues, please raise an issue in Typescript repo or put it on Stackoverflow.

Closing this issue as it isn't related to `redis-json` library
